send_action:
  name: Send Action
  description: Send an action to the Asterisk Manager Interface.
  fields:
    action:
      name: Action
      description: Action to send.
      required: true
      example: "Ping"
      selector:
        text:
    parameters:
      name: Parameters
      description: Parameters to send with the action.
      required: true
      example: "key: val"
      selector:
        object: